### ISSUE TITLE
Can not open the modifider 2.1.1 successfully

### ISSUE THREAD

**Issue by JetZ1216** [cfogrady/DIM-Modifier#51]
When I click the DIM Modifider 2.1.0 and 2.1.1  It flashback immediately.  It doesn't happend on the old version.  I have tried by three different computer and different system. Not work, How can I run it . Should I install something? Best wishes~

**Comment by JetZ1216** [comment]
The flashback comes very fast. I can't see what the command prompt. I just screenshot a picture.&nbsp; When this command finshed. The program was killed.





Sniper→小傑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cfogrady/DIM-Modifier"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 晚上10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cfogrady/DIM-Modifier] Can not open the modifider 2.1.1 successfully (Issue #51)





 
Very strange. Can you run it from a command prompt and paste the command prompt output here?

**Comment by cfogrady** [comment]
Sorry,
I meant open command prompt from your computer, navigate to the DIM-Modifier program and type the executable in the command prompt to run it from the command prompt. That should result in all the logs going to the open command prompt window that you ran it from.

**Comment by JetZ1216** [comment]
I tried it. But it doesn‘t work. Stuck in command prompt and can not open the program.







Sniper→小傑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cfogrady/DIM-Modifier"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 晚上10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cfogrady/DIM-Modifier] Can not open the modifider 2.1.1 successfully (Issue #51)





 
Sorry,
 I meant open command prompt from your computer, navigate to the DIM-Modifier program and type the executable in the command prompt to run it from the command prompt. That should result in all the logs going to the open command prompt window that you ran it from.

**Comment by cfogrady** [comment]
Try taking a screen recording of you opening it, then see if you can get the frames that show the command prompt or you can send the video to me and I can try to get those frames.

**Comment by JetZ1216** [comment]
I put the video into the attachment. 3 different computer , same problem.




Sniper→小傑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cfogrady/DIM-Modifier"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 晚上11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cfogrady/DIM-Modifier] Can not open the modifider 2.1.1 successfully (Issue #51)





 
Try taking a screen recording of you opening it, then see if you can get the frames that show the command prompt or you can send the video to me and I can try to get those frames.

**Comment by cfogrady** [comment]
I don't think email attachments are being connected to the GitHub issue, so I'm not seeing them. Can you try adding the video directly to this issue in GitHub?

**Comment by JetZ1216** [comment]
https://github.com/cfogrady/DIM-Modifier/assets/154441543/61246e32-fd3b-40b1-b88c-38da9770f6e4

**Comment by cfogrady** [comment]
Interesting. I can't reproduce, but I can say it's having an issue loading your firmware file.
Delete "HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\github\cfogrady\dim\modifier" from your registry.
That should clear the preferences and allow it to restart with the select firmware location screen. From there, just select an official firmware file, and then the DIM files you want to modify.

Let me know if that works.

**Comment by cfogrady** [comment]
Think I reproduced. I closed out of the program after a failed firmware load instead of selecting a new firmware. Clearing the registry still worked. Adding this log output so I can take a look at fixing in the future:

```
[JavaFX Application Thread] ERROR com.github.cfogrady.dim.modifier.Main - Unable to load firmware. Please select firmware location.
java.lang.IllegalArgumentException: Expecting VBBE_10B.vb2 or VBBE_20A.vb2 firmware file.
        at DIM.Modifier.main@2.0.3/com.github.cfogrady.dim.modifier.data.firmware.FirmwareManager.loadFirmware(FirmwareManager.java:55)
        at DIM.Modifier.main@2.0.3/com.github.cfogrady.dim.modifier.Main.loadFirstScene(Main.java:43)
        at DIM.Modifier.main@2.0.3/com.github.cfogrady.dim.modifier.Main.start(Main.java:30)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Thread.java:833)
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:465)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException
        at java.prefs/java.util.prefs.AbstractPreferences.put(AbstractPreferences.java:249)
        at DIM.Modifier.main@2.0.3/com.github.cfogrady.dim.modifier.data.firmware.FirmwareManager.clearFirmwareLocation(FirmwareManager.java:29)
        at DIM.Modifier.main@2.0.3/com.github.cfogrady.dim.modifier.Main.loadFirstScene(Main.java:50)
        at DIM.Modifier.main@2.0.3/com.github.cfogrady.dim.modifier.Main.start(Main.java:30)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        ... 1 more
Exception running application com.github.cfogrady.dim.modifier.Main
```

**Comment by JetZ1216** [comment]
Doesn‘t work... This is my another computer ， same situation.

**Comment by JetZ1216** [comment]
https://github.com/cfogrady/DIM-Modifier/assets/154441543/3efda4ee-31d1-4403-875d-8d2ef4979f25

This is my another computer, same suitation

**Comment by JetZ1216** [comment]
Oh I solve it.  delete the registry！ Work！
